### ISSUE TITLE
update version of JWPlayer used in the repo

### ISSUE THREAD

**Issue by somerobmitchell** [Vualto/vuplay-jwplayer#3]
The version of JWPlayer used in this demo repo should be updated to the latest version available.

**Comment by rogerpales** [comment]
adding into that `https://cdn.vuplay.co.uk/jwplayer/8.7.6/jwplayer.js` is not publicly available if there

**Comment by somerobmitchell** [comment]
https://github.com/Vualto/vuplay-jwplayer/pull/11
